export const homeObjOne = {
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Bank',
    headline:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Get started',
    imgStart:false,
    img:require('../../images/car.svg').default,
    alt:'Car',
    dark:true,
    primary:true,
    darkText:false,
}
export const homeObjTwo = {
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Unlimited Access',
    headline:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Learn More',
    imgStart:true,
    img:require('../../images/1.svg').default,
    alt:'Piggy',
    dark:false,
    primary:false,
    darkText:true,
}
export const homeObjThree = {
    id:'signup',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Premium Bank',
    headline:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Start Now',
    imgStart:false,
    img:require('../../images/work.svg').default,
    alt:'Paper',
    dark:false,
    primary:false,
    darkText:true,
}
export const homeObjFour = {
    id:'signup',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Bank',
    headline:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Start Now',
    imgStart:false,
    img:require('../../images/2.svg').default,
    alt:'Paper',
    dark:true,
    primary:true,
    darkText:false,
}
export const homeObjFive = {
    id:'signup',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Premium Bank',
    headline:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Start Now',
    imgStart:false,
    img:require('../../images/3.svg').default,
    alt:'Paper',
    dark:false,
    primary:false,
    darkText:true,
}

